# Generated by Django 5.2 on 2025-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='Income', max_length=100),
            preserve_default=False,
        ),
    ]
